# Generated by Django 5.1.15 on 2026-03-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_course'),
        ('accounts', '0006_alter_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_mark', models.FloatField()),
                ('theoretical_mark', models.FloatField()),
                ('status', models.CharField(choices=[('DROPPED', 'Dropped'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ONGOING', 'Ongoing'), ('REGISTERED', 'Registered')], default='ONGOING', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
