# Generated by Django 5.1.15 on 2026-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='practical_mark',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('DROPPED', 'Dropped'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ONGOING', 'Ongoing'), ('REGISTERED', 'Registered')], default='REGISTERED', max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='theoretical_mark',
            field=models.FloatField(default=0.0),
        ),
    ]
