# Generated by Django 5.1.15 on 2026-02-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('teacher_assistant', 'Teacher Assistant'), ('employee', 'Employee'), ('student', 'Student')], default='employee', max_length=20),
        ),
    ]
