# Generated by Django 5.1.15 on 2026-02-22 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_number', models.CharField(max_length=20, unique=True)),
                ('gpa', models.FloatField(default=0.0)),
                ('year', models.CharField(choices=[('1st', 'First Year'), ('2ed', 'Second Year'), ('3ed', 'Third Year'), ('4th', 'Fourth Year'), ('5th', 'Fifth Year'), ('6th', 'Sixth Year')], default='1st', max_length=14)),
                ('major', models.CharField(choices=[('CS', 'Computer Science'), ('AI', 'Artificial Intelligence'), ('SE', 'Software Engineering'), ('NE', 'Networking Engineering')], default='CS', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
