# Generated by Django 5.1.15 on 2026-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_number',
            field=models.CharField(max_length=20),
        ),
    ]
