# Generated by Django 5.1.15 on 2026-02-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_university_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
