# Generated by Django 5.1.15 on 2026-03-02 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('UNI_MAND', 'University Mandatory'), ('UNI_ELEC', 'University Elective'), ('COL_MAND', 'College Mandatory'), ('COL_ELEC', 'College Elective'), ('DEP_MAND', 'Department Mandatory'), ('DEP_ELEC', 'Department Elective')], default='COL_MAND', max_length=50)),
                ('credit_hours', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('description', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=10)),
                ('hours_pre_requisites', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(165)])),
                ('departments', models.ManyToManyField(related_name='academics', to='academics.department')),
                ('subjects_pre_requisites', models.ManyToManyField(related_name='opens', to='academics.subject')),
            ],
        ),
    ]
