# Generated by Django 5.1.15 on 2026-03-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_dep_approval_pre_requisite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjects_pre_requisites',
            field=models.ManyToManyField(blank=True, related_name='opens', to='academics.subject'),
        ),
    ]
