# Generated by Django 5.1.15 on 2026-03-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_subject_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('SUMMER', 'Summer')], default='FIRST', max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('is_open', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
